<a href="https://colab.research.google.com/github/Katbut/Homework/blob/main/%D0%94%D0%B76.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.


In [2]:
import numpy as np
import pandas as pd

zp =np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [3]:
ks=np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [4]:
c=(zp*ks).mean()-zp.mean()*ks.mean()
c

9157.839999999997

In [5]:
np.cov(zp,ks) [0,1]

10175.377777777776

In [6]:
np.cov(zp,ks,ddof=0) [0,1]

9157.84

In [7]:
df=pd.DataFrame({'zp':zp,'ks':ks}, columns=['zp','ks'])
df

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459
5   70  739
6   54  653
7  150  902
8  120  746
9  110  832

In [8]:
df.cov().values[0,1]

10175.377777777776

In [9]:
df.corr()

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

In [10]:
ks.std(ddof=1)

183.99544076477068

In [11]:
10175.3777/(ks.std(ddof=1)*zp.std(ddof=1))

0.8874900852901869

In [13]:
9157/(ks.std()*zp.std())

0.8874086873237411

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [15]:
iq =np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
iq

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [16]:
iq.mean()

118.1

In [17]:
alpha2=0.05/2
alpha2

0.025

In [18]:
df = len(iq)-1
df

9

In [19]:
t=2.262

In [20]:
iq.mean()-(t*(iq.std(ddof=1))/((10)**0.5))

110.55660776308164

In [21]:
iq.mean()+(t*(iq.std(ddof=1))/((10)**0.5))

125.64339223691834

Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [22]:
std=5

In [23]:
n=27

In [24]:
mu=174.2

In [25]:
alpha2=0.05/2
alpha2

0.025

In [27]:
z_t=1.96

In [28]:
mu-(z_t*std/(27)**0.5)

172.31398912064722

In [29]:
mu+(z_t*std/(27)**0.5)

176.08601087935276

Задание 4. Выбрать тему курсового проекта."В проектной работе хотела бы сделать анализ цен на нефть  и газ в мире (https://www.kaggle.com/datasets/zusmani/petrolgas-prices-worldwide)
Рассчитать основные статистические показатели: Мода, медиана, квартили, дисперсию.
Проверить, работает ли нормальное распределение и Паретто.
Проверить есть ли зависимость между ежедневным потреблением и ценой на топливо.