<a href="https://colab.research.google.com/github/Katbut/Homework/blob/main/%D0%94%D0%B7_2_1_%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
A = np.array([[1, -2], [3,0]])
B = np.array([[4, -1], [0,5]])


print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')

print(f'Сумма матриц A+B\n{A+B}')

print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица ВА\n{B.dot(A)}')


Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Сумма матриц A+B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица ВА
[[ 1 -8]
 [15  0]]


In [6]:
A = np.array([[1, 7], [3,-6]])
B = np.array([[0, 5], [2,-1]])
C = np.array([[2, -4], [1,1]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица C\n{C}')
print(f'Подсчет 3А-2В+4С')

x=3
y=-2
z=4

print(f'решение\n{x*A+y*B+z*C}')


Матрица A
[[ 1  7]
 [ 3 -6]]
Матрица B
[[ 0  5]
 [ 2 -1]]
Матрица C
[[ 2 -4]
 [ 1  1]]
Подсчет 3А-2В+4С
решение
[[ 11  -5]
 [  9 -12]]


In [7]:
a = np.array([[4,1], [5,-2], [2,3]])

print(f'Матрица:\n{a}')
print(f'Транспонированная матрица:\n{a.T}')

print(f'результат а*аТ:\n{np.dot(a, a.T)}')
print(f'результат аТ*а:\n{np.dot(a.T, a)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
результат а*аТ:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
результат аТ*а:
[[45  0]
 [ 0 14]]
