<a href="https://colab.research.google.com/github/Katbut/Homework/blob/main/%D0%94%D0%B77.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
x=np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
x

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [4]:
y=np.array( [401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [6]:
n=len(x)
n

10

In [11]:
b=(np.mean(x*y)-np.mean(x)*np.mean(y))/(np.mean(x**2)-np.mean(x)**2)
b

2.620538882402765

In [12]:
a=np.mean(y)-b*np.mean(x)
a

444.1773573243596

In [13]:
x=x.reshape((10,1))
x

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [14]:
y=y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [18]:
B=np.dot(np.linalg.inv(np.dot(x.T,x)),x.T @ y)
B 

array([[5.88982042]])

с интерсептом

In [19]:
x=np.hstack([np.ones((10,1)),x])
x

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [20]:
B=np.dot(np.linalg.inv(np.dot(x.T,x)),x.T @ y)
B 

array([[444.17735732],
       [  2.62053888]])